# Generated by Django 2.2.3 on 2019-07-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='swiped',
            table='swiped',
        ),
    ]
