# Generated by Django 2.2.3 on 2019-07-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190704_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sz', '深圳'), ('sh', '上海'), ('gz', '广州'), ('cd', '成都'), ('dl', '大连')], max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(choices=[('bj', '北京'), ('sz', '深圳'), ('sh', '上海'), ('gz', '广州'), ('cd', '成都'), ('dl', '大连')], max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.IntegerField(choices=[(0, '全部'), (1, '男'), (2, '女')], default=0),
        ),
    ]
