# Generated by Django 2.2.3 on 2019-07-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190706_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='vip_id',
            field=models.IntegerField(default=1),
        ),
    ]
